name: Build and deploy an updated version of the website

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pandocs
      uses: actions/checkout@v2
      with:
        path: pandocs

    - name: Install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Install mdbook-linkcheck
      run: |
        cargo install mdbook-linkcheck
        mdbook-linkcheck --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pandocs/requirements.txt

    - name: Build
      working-directory: pandocs/
      env:
        MDBOOK_BUILD__CREATE_MISSING: "false" # Prevent creating missing files in SUMMARY.md
      run: |
        mdbook build

    - name: Deploy
      # Do not run this unless *pushing* (`heads`) to `master`
      if: github.ref == 'refs/heads/master'
      working-directory: pandocs/docs/pandocs/
      run: |
        mkdir -p -m 700 ~/.ssh
        cat <<EOF > ~/.ssh/id_ed25519
        ${{ secrets.SSH_KEY_SECRET }}
        EOF
        chmod 0600 ~/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        if ! ssh-add -v ~/.ssh/id_ed25519; then
          echo Looks like no deploy key has been set, skipping deploy.
          exit 0
        fi
        # Set up repo
        git init
        git config --local user.name "GitHub Action"
        git config --global user.email "community@gbdev.io"
        # Create local branch tracking remote gh-pages branch
        git remote add origin git@github.com:${{ github.repository }}.git
        git remote -v
        git fetch
        git branch gh-pages origin/gh-pages
        # Create dummy commit to detach to
        git add -A
        git commit -m "tmp"
        # Switch to gh-pages branch without changing the tree
        git checkout --detach
        git reset --soft gh-pages
        git checkout gh-pages
        # Commit & push changes
        git commit -am 'Update build'
        git push -v
